#!/usr/bin/env python3
"""Convert 16kHz 16-bit mono WAV files to a C header for ESP32 sound system.

Usage:
    python tools/wav_to_c.py tools/fish_voice/ firmware/src/fish_sounds.h
"""
import os, sys, wave, struct

def wav_to_samples(path):
    with wave.open(path, 'rb') as w:
        nch, sw, rate, nframes, _, _ = w.getparams()
        assert sw == 2, f"{path}: expected 16-bit PCM, got {sw*8}-bit"
        assert nch == 1, f"{path}: expected mono, got {nch} channels"
        raw = w.readframes(nframes)
    samples = struct.unpack(f'<{nframes}h', raw)
    return samples, rate

def resample_linear(samples, orig_rate, target_rate):
    if orig_rate == target_rate:
        return samples
    ratio = orig_rate / target_rate
    n_out = int(len(samples) / ratio)
    out = []
    for i in range(n_out):
        pos = i * ratio
        idx = int(pos)
        frac = pos - idx
        s0 = samples[idx]
        s1 = samples[idx + 1] if idx + 1 < len(samples) else s0
        out.append(int(s0 + frac * (s1 - s0)))
    return out

def samples_to_c(name, samples):
    lines = [f'static const int16_t {name}[{len(samples)}] = {{']
    row = []
    for i, s in enumerate(samples):
        row.append(f'{s}')
        if len(row) == 12:
            lines.append('    ' + ', '.join(row) + ',')
            row = []
    if row:
        lines.append('    ' + ', '.join(row) + ',')
    lines.append('};')
    lines.append(f'static const int {name}_len = {len(samples)};')
    return '\n'.join(lines)

TARGET_RATE = 16000

CLIP_ORDER = ['fish_idle', 'fish_norm', 'fish_active', 'fish_heavy']

def main():
    in_dir  = sys.argv[1] if len(sys.argv) > 1 else 'tools/fish_voice'
    out_hdr = sys.argv[2] if len(sys.argv) > 2 else 'firmware/src/fish_sounds.h'

    chunks = []
    for name in CLIP_ORDER:
        path = os.path.join(in_dir, f'{name}.wav')
        if not os.path.exists(path):
            print(f'WARNING: {path} not found, skipping')
            continue
        samples, rate = wav_to_samples(path)
        if rate != TARGET_RATE:
            print(f'  resampling {name}: {rate}Hz -> {TARGET_RATE}Hz')
            samples = resample_linear(samples, rate, TARGET_RATE)
        dur = len(samples) / TARGET_RATE
        print(f'  {name}: {len(samples)} samples ({dur:.2f}s, {len(samples)*2//1024}KB)')
        chunks.append(samples_to_c(name, samples))

    header = '\n'.join([
        '#pragma once',
        '#include <stdint.h>',
        '',
        '// Auto-generated by tools/wav_to_c.py - do not hand-edit.',
        '// 16 kHz 16-bit mono PCM for fish-personality splash voice.',
        '',
    ] + [c + '\n' for c in chunks])

    with open(out_hdr, 'w', encoding='utf-8') as f:
        f.write(header)
    print(f'wrote {out_hdr}')

if __name__ == '__main__':
    main()
